import { defineConfig } from 'tsdown'

export default defineConfig([
  {
    entry: 'src/index.ts',
    format: 'cjs',
    dts: true,
    outDir: 'dist/cjs',
    sourcemap: true,
    clean: true,
    minify: false,
    target: 'es2015',
    platform: 'node',
    shims: true,
  },
  {
    entry: 'src/index.ts',
    format: 'esm',
    dts: true,
    outDir: 'dist/esm',
    sourcemap: true,
    clean: true,
    minify: false,
    target: 'es2015',
    platform: 'neutral',
    shims: true,
  },
  {
    entry: 'src/index.ts',
    format: 'umd',
    dts: true,
    outDir: 'dist/umd',
    sourcemap: true,
    clean: true,
    globalName: 'LnurlPay',
    minify: true,
    target: 'es2015',
    platform: 'browser',
    shims: true,
    banner: { js: '// lnurl-pay UMD bundle' },
    external: [
      'is-url',
      'bech32',
      'axios',
      'aes-js',
      'base64-js',
      'bolt11',
      '@aws-crypto/sha256-js',
    ],
  },
])
